name: Articlesnatch
favicon: null
layout_spectrum: 0.35618929215706885
typography_spectrum: 0.6400812286883593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2022824443411082
  lightness: 0.2674565289635211
  saturation: 0.28089168411679566
  rhythmicContrast: 0.664049653802067
purpose: []
